name: review_detect
channels:
  - conda-forge
dependencies:
  - python=3.8
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pip
  - pip:
      - torch
      - transformers
      - datasets
      - tqdm
      - accelerate>=0.26.0 